# Site settings
title: Tim Rourke's General Assembly Portfolio
email: tim@timrourke.com
description: > # this means to ignore newlines until "baseurl:"
  On June 29th, 2015, I embarked on a new adventure. I've joined the 2nd-ever
  Chicago cohort of General Assembly's Web Development Intensive program.
baseurl: "/_site/" # the subpath of your site, e.g. /blog/
url: "http://timrourke.github.io" # the base hostname & protocol for your site
twitter_username: RourkeTim
github_username:  timrourke

# Build settings
markdown: kramdown
